import '$/app/globals.css'

import { PageTransition } from '$/components/PageTransition'
import { PanesLayer } from '$/components/PanesLayer'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="'text-black bg-gray-50 dark:text-white dark:bg-[#111010]',">
      <body >
        <main >
          <PageTransition>{children}</PageTransition>
          <PanesLayer />
        </main>
      </body>
    </html>
  )
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
